name: vbtutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=20.1.0=py37hcc03f2d_2
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bleach=3.3.0=pyh44b312d_0
  - ca-certificates=2021.5.30=h5b45459_0
  - certifi=2021.5.30=py37h03978a9_0
  - cffi=1.14.5=py37hd8e9650_0
  - colorama=0.4.4=pyh9f0ad1d_0
  - cycler=0.10.0=py_2
  - decorator=5.0.9=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - freetype=2.10.4=h546665d_1
  - icu=68.1=h0e60522_0
  - importlib-metadata=4.6.0=py37h03978a9_0
  - intel-openmp=2021.2.0=h57928b3_616
  - ipykernel=5.5.5=py37h7813e69_0
  - ipython=7.25.0=py37h7813e69_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.6.3=pyhd3deb0d_0
  - jbig=2.1=h8d14728_2003
  - jedi=0.18.0=py37h03978a9_2
  - jinja2=3.0.1=pyhd8ed1ab_0
  - jpeg=9d=h8ffe710_0
  - jsonschema=3.2.0=pyhd8ed1ab_3
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.7.1=py37h03978a9_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_widgets=1.0.0=pyhd8ed1ab_1
  - kiwisolver=1.3.1=py37h8c56517_1
  - lcms2=2.12=h2a16943_0
  - lerc=2.2.1=h0e60522_0
  - libblas=3.9.0=9_mkl
  - libcblas=3.9.0=9_mkl
  - libclang=11.1.0=default_h5c34c98_1
  - libdeflate=1.7=h8ffe710_5
  - liblapack=3.9.0=9_mkl
  - libpng=1.6.37=h1d00b33_2
  - libsodium=1.0.18=h8d14728_1
  - libtiff=4.3.0=h0c97f57_1
  - lz4-c=1.9.3=h8ffe710_0
  - markupsafe=2.0.1=py37hcc03f2d_0
  - matplotlib=3.4.2=py37h03978a9_0
  - matplotlib-base=3.4.2=py37h0d1fb12_0
  - matplotlib-inline=0.1.2=pyhd8ed1ab_2
  - mistune=0.8.4=py37hcc03f2d_1004
  - mkl=2021.2.0=hb70f87d_389
  - nbclient=0.5.3=pyhd8ed1ab_0
  - nbconvert=6.1.0=py37h03978a9_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - notebook=6.4.0=pyha770c72_0
  - numpy=1.21.0=py37hcbcd69c_0
  - olefile=0.46=pyh9f0ad1d_1
  - openjpeg=2.4.0=hb211442_1
  - openssl=1.1.1k=h8ffe710_0
  - packaging=20.9=pyh44b312d_0
  - pandoc=2.14.0.3=h8ffe710_0
  - pandocfilters=1.4.2=py_1
  - parso=0.8.2=pyhd8ed1ab_0
  - pickleshare=0.7.5=py_1003
  - pillow=8.2.0=py37h96663a1_1
  - pip=21.1.3=pyhd8ed1ab_0
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.19=pyha770c72_0
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.9.0=pyhd8ed1ab_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.12.3=py37h03978a9_7
  - pyqt-impl=5.12.3=py37hf2a7229_7
  - pyqt5-sip=4.19.18=py37hf2a7229_7
  - pyqtchart=5.12=py37hf2a7229_7
  - pyqtwebengine=5.12.1=py37hf2a7229_7
  - pyrsistent=0.17.3=py37hcc03f2d_2
  - python=3.7.10=h7840368_100_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=2_cp37m
  - pywin32=300=py37hcc03f2d_0
  - pywinpty=1.1.3=py37h7f67f24_0
  - pyzmq=22.1.0=py37hcce574b_0
  - qt=5.12.9=h5909a2a_4
  - send2trash=1.7.1=pyhd8ed1ab_0
  - setuptools=49.6.0=py37h03978a9_3
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.36.0=h8ffe710_0
  - tbb=2021.2.0=h2d74725_1
  - terminado=0.10.1=py37h03978a9_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - tk=8.6.10=h8ffe710_1
  - tornado=6.1=py37hcc03f2d_1
  - traitlets=5.0.5=py_0
  - typing_extensions=3.10.0.0=pyha770c72_0
  - ucrt=10.0.20348.0=h57928b3_0
  - vc=14.2=hb210afc_5
  - vs2015_runtime=14.29.30037=h902a5da_5
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.36.2=pyhd3deb0d_0
  - widgetsnbextension=3.5.1=py37h03978a9_4
  - wincertstore=0.2=py37h03978a9_1006
  - winpty=0.4.3=4
  - xz=5.2.5=h62dcd97_1
  - zeromq=4.3.4=h0e60522_0
  - zipp=3.4.1=pyhd8ed1ab_0
  - zlib=1.2.11=h62dcd97_1010
  - zstd=1.5.0=h6255e5f_0
prefix: C:\Users\jacka\.conda\envs\vbtutorial
